- id: fix-smartquotes
  name: Fix smartquote characters
  description: 'Replace "smartquote" characters with regular quotes'
  entry: fix-smartquotes
  language: python
  types: [text]
- id: fix-ligatures
  name: Fix ligature characters with NFKD normalization
  description: 'Replace ligature characters with normalized individual characters'
  entry: fix-ligatures
  language: python
  types: [text]
